# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loanGivenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='loanNeededModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('interest', models.IntegerField(default=0)),
                ('tenure', models.IntegerField(default=0)),
                ('riskCategory', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='profileModel',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('aadhar', models.CharField(max_length=20)),
                ('gender', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dob', models.CharField(max_length=20)),
                ('facebookID', models.CharField(max_length=50)),
                ('twitterID', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('creditRating', models.CharField(max_length=5)),
                ('interestRate', models.IntegerField(default=0)),
                ('isBorrower', models.BooleanField(default=True)),
                ('facebook_twitter', models.IntegerField(blank=True, null=True)),
                ('postpaid', models.IntegerField(blank=True, null=True)),
                ('late_bill_days_avg', models.IntegerField(blank=True, null=True)),
                ('Education', models.IntegerField(blank=True, null=True)),
                ('similar_locations', models.IntegerField(blank=True, null=True)),
                ('network_bytes', models.IntegerField(blank=True, null=True)),
                ('daily_sms', models.IntegerField(blank=True, null=True)),
                ('usage_hours_per_week', models.IntegerField(blank=True, null=True)),
                ('pan', models.IntegerField(blank=True, null=True)),
                ('Property_Area', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='loanneededmodel',
            name='personID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIs.profileModel'),
        ),
        migrations.AddField(
            model_name='loangivenmodel',
            name='loanID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIs.loanNeededModel'),
        ),
        migrations.AddField(
            model_name='loangivenmodel',
            name='personID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIs.profileModel'),
        ),
    ]
