# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanneededmodel',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
